04-25 23:22:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Method is only allowed for a query. Use execute or executeUpdate instead of executeQuery; SQL statement:
CREATE TABLE TEST(ID INT PRIMARY KEY, NAME VARCHAR(255)); [90002-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.command.Prepared.query(Prepared.java:213)
	at org.h2.command.CommandContainer.query(CommandContainer.java:91)
	at org.h2.command.Command.executeQuery(Command.java:197)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:81)
	at data.DataManager.InsertRow(DataManager.java:32)
	at data.Recorder.main(Recorder.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
	at com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
04-25 23:54:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE EXPERIMENT (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
GENDER BIT NOT NULL,
DOMINANT_HAND BIT NOT NULL,
COUNT INT NOT NULL,
TIME_EXP1 INT NOT NULL,
TIME_EXP2 INT NOT NULL,
TIME_EXP3 INT NOT NULL,
FILE VARCHAR(255) NOT NULL)
 


                   INT[*] NOT NULL REFERENCES PLAYERS(PLAYERID),
                  ADDED TIMESTAMP AS CURRENT_TIMESTAMP NOT NULL) "; SQL statement:
create table EXPERIMENT (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
GENDER BIT NOT NULL,
DOMINANT_HAND BIT NOT NULL,
COUNT INT NOT NULL,
TIME_EXP1 INT NOT NULL,
TIME_EXP2 INT NOT NULL,
TIME_EXP3 INT NOT NULL,
FILE VARCHAR(255) NOT NULL)
 


                   INT NOT NULL REFERENCES players(playerid),
                  added TIMESTAMP AS CURRENT_TIMESTAMP NOT NULL) [42000-176]
04-26 00:06:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP CONSTRAINT[*] WHAT"; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE"; SQL statement:
DROP CONSTRAINT WHAT [42001-176]
04-26 00:14:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
INSERT INTO EXPERIMENT VALUES (0, 1, 3,  25, 30, 40, "201413121239.data") [21002-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.command.dml.Insert.prepare(Insert.java:266)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-26 00:16:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "201413121239.data" not found; SQL statement:
INSERT INTO EXPERIMENT (GENDER, DOMINANT_HAND, COUNT, TIME_EXP1, TIME_EXP2, TIME_EXP3, FILE)
VALUES (0, 1, 3,  25, 30, 40, "201413121239.data") [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-26 00:16:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "201413121239.data" not found; SQL statement:
INSERT INTO EXPERIMENT (GENDER, DOMINANT_HAND, COUNT, TIME_EXP1, TIME_EXP2, TIME_EXP3,  FILE)
VALUES (0, 1, 3,  25, 30, 40, "201413121239.data") [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-26 00:16:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "201413121239" not found; SQL statement:
INSERT INTO EXPERIMENT (GENDER, DOMINANT_HAND, COUNT, TIME_EXP1, TIME_EXP2, TIME_EXP3,  FILE)
VALUES (0, 1, 3,  25, 30, 40, "201413121239") [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-26 00:16:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "201413121239" not found; SQL statement:
INSERT INTO EXPERIMENT (GENDER, DOMINANT_HAND, COUNT, TIME_EXP1, TIME_EXP2, TIME_EXP3,  FILE)
VALUES (0, 1, 3,  25, 30, 40, "201413121239") [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-26 00:16:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "201413121239" not found; SQL statement:
INSERT INTO EXPERIMENT (GENDER, DOMINANT_HAND, COUNT, TIME_EXP1, TIME_EXP2, TIME_EXP3,  FILE)
VALUES (0, 1, 3,  25, 30, 40, "201413121239") [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-26 00:17:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
INSERT INTO EXPERIMENT
VALUES (0, 1, 3,  25, 30, 40, '201413121239') [21002-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.command.dml.Insert.prepare(Insert.java:266)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-26 00:38:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECTION[*] * FROM EXPERIMENT "; expected "SELECT, SET, SAVEPOINT, SCRIPT, SHUTDOWN, SHOW, {"; SQL statement:
Selection * From EXPERIMENT [42001-176]
04-26 01:09:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (EXPERIMENT: ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6D5E8DEA_8E28_4403_B464_80E485017233) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6D5E8DEA_8E28_4403_B464_80E485017233)"; SQL statement:
INSERT INTO "PUBLIC"."EXPERIMENT"("ID","GENDER","DOMINANT_HAND","TIME_T1","TIME_T2","TIME_T3","TIME_R1","TIME_R2","TIME_R3","TIME_S1","TIME_S2","TIME_S3","FILE")VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13) [22018-176]
04-26 01:09:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (EXPERIMENT: ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6D5E8DEA_8E28_4403_B464_80E485017233) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6D5E8DEA_8E28_4403_B464_80E485017233)"; SQL statement:
INSERT INTO "PUBLIC"."EXPERIMENT"("ID","GENDER","DOMINANT_HAND","TIME_T1","TIME_T2","TIME_T3","TIME_R1","TIME_R2","TIME_R3","TIME_S1","TIME_S2","TIME_S3","FILE")VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13) [22018-176]
04-26 01:09:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (EXPERIMENT: ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6D5E8DEA_8E28_4403_B464_80E485017233) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6D5E8DEA_8E28_4403_B464_80E485017233)"; SQL statement:
INSERT INTO "PUBLIC"."EXPERIMENT"("ID","GENDER","DOMINANT_HAND","TIME_T1","TIME_T2","TIME_T3","TIME_R1","TIME_R2","TIME_R3","TIME_S1","TIME_S2","TIME_S3","FILE")VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13) [22018-176]
04-26 01:09:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (EXPERIMENT: ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6D5E8DEA_8E28_4403_B464_80E485017233) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_6D5E8DEA_8E28_4403_B464_80E485017233)"; SQL statement:
INSERT INTO "PUBLIC"."EXPERIMENT"("ID","GENDER","DOMINANT_HAND","TIME_T1","TIME_T2","TIME_T3","TIME_R1","TIME_R2","TIME_R3","TIME_S1","TIME_S2","TIME_S3","FILE")VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13) [22018-176]
04-26 01:23:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO EXPERIMENT (GENDER, DOMINANT_HAND, FILE, TIME_T1, TIME_T2 , TIME_T3 , TIME_R1 , TIME_R2 , TIME_R3 , TIME_S1 , TIME_S2 , TIME_S3)VALUES (1,0,2015425.DATA[*],4,3,2,5,4,3,3,2,1); "; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO EXPERIMENT (GENDER, DOMINANT_HAND, FILE, TIME_T1, TIME_T2 , TIME_T3 , TIME_R1 , TIME_R2 , TIME_R3 , TIME_S1 , TIME_S2 , TIME_S3)VALUES (1,0,2015425.data,4,3,2,5,4,3,3,2,1); [42001-176]
04-26 01:24:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO EXPERIMENT (GENDER, DOMINANT_HAND, FILE, TIME_T1, TIME_T2 , TIME_T3 , TIME_R1 , TIME_R2 , TIME_R3 , TIME_S1 , TIME_S2 , TIME_S3)VALUES (1,0,2015425.DATA[*],4,3,2,5,4,3,3,2,1); "; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO EXPERIMENT (GENDER, DOMINANT_HAND, FILE, TIME_T1, TIME_T2 , TIME_T3 , TIME_R1 , TIME_R2 , TIME_R3 , TIME_S1 , TIME_S2 , TIME_S3)VALUES (1,0,2015425.data,4,3,2,5,4,3,3,2,1); [42001-176]
04-26 01:24:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO EXPERIMENT (GENDER, DOMINANT_HAND, FILE, TIME_T1, TIME_T2 , TIME_T3 , TIME_R1 , TIME_R2 , TIME_R3 , TIME_S1 , TIME_S2 , TIME_S3)VALUES (1,0,2015425.DATA[*],4,3,2,5,4,3,3,2,1) "; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO EXPERIMENT (GENDER, DOMINANT_HAND, FILE, TIME_T1, TIME_T2 , TIME_T3 , TIME_R1 , TIME_R2 , TIME_R3 , TIME_S1 , TIME_S2 , TIME_S3)VALUES (1,0,2015425.data,4,3,2,5,4,3,3,2,1) [42001-176]
05-06 10:20:02 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "EXPERIENCE" not found; SQL statement:
DROP TABLE EXPERIENCE [42102-176]
05-06 10:25:39 jdbc[5]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:684)
	at org.h2.server.web.WebApp.login(WebApp.java:958)
	at org.h2.server.web.WebApp.process(WebApp.java:212)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:171)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 14 more
05-06 13:52:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (EXPERIMENT: ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_8ADB46AE_2E5F_475B_8A17_B57818C0335D) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8ADB46AE_2E5F_475B_8A17_B57818C0335D)"; SQL statement:
INSERT INTO "PUBLIC"."EXPERIMENT"("ID","DOMINANT_HAND","FILE","MODE1","TIME1","MODE2","TIME2","MODE3","TIME3","MODE4","TIME4","MODE5","TIME5","MODE6","TIME6","MODE7","TIME7","MODE8","TIME8","MODE9","TIME9")VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21) [22018-176]
05-06 13:52:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (EXPERIMENT: ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_8ADB46AE_2E5F_475B_8A17_B57818C0335D) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8ADB46AE_2E5F_475B_8A17_B57818C0335D)"; SQL statement:
INSERT INTO "PUBLIC"."EXPERIMENT"("ID","DOMINANT_HAND","FILE","MODE1","TIME1","MODE2","TIME2","MODE3","TIME3","MODE4","TIME4","MODE5","TIME5","MODE6","TIME6","MODE7","TIME7","MODE8","TIME8","MODE9","TIME9")VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21) [22018-176]
